;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        comment-line
        end-of-visual-line
        haskell-indentation-common-electric-command
        haskell-indentation-newline-and-indent
        hungry-delete-backward
        hungry-delete-forward
        hydra-mc/mc/reverse-regions
        hydra-mc/mc/sort-regions
        hydra-mc/nil
        indent-for-tab-command
        lsp-ui-doc--handle-mouse-movement
        org-self-insert-command
        org-shiftright
        purescript-indentation-delete-backward-char
        purescript-indentation-delete-char
        smarter-move-beginning-of-line
        sp-unwrap-sexp
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        helm-confirm-and-exit-minibuffer
        helm-show-kill-ring
        hydra-mc/body
        hydra-mc/mc/insert-numbers
        hydra-mc/mc/mark-next-like-this
        hydra-mc/mc/mark-next-like-this-and-exit
        hydra-mc/mc/mark-previous-like-this
        hydra-mc/mc/mark-previous-like-this-and-exit
        hydra-mc/mc/skip-to-next-like-this
        hydra-mc/mc/skip-to-previous-like-this
        hydra-mc/mc/unmark-next-like-this
        hydra-mc/mc/unmark-previous-like-this
        kill-region
        ))
